CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","EN GALICIA");
CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","AL NOROESTE DE LA PENÍNSULA IBÉRICA");
CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","AL SUR DE GALICIA");
CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","EN LAS RÌAS BAJAS DE GALICIA");
CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","A 100 KM DE SANTIAGO");
CALL INSERT_PREGUNTA_RESPUESTA ("DÓNDE ESTÁ VIGO?","EN EL NOROESTE DE ESPAÑA");


SELECT GET_RESPUESTA_FROM_PREGUNTA ("SOY GUAPO?");
SELECT GET_RESPUESTA_FROM_PREGUNTA (NULL);
SELECT GET_RESPUESTA_FROM_PREGUNTA ("DÓNDE ESTÁ VIGO?");

SELECT  CADENA_RESPUESTA
    FROM RESPUESTAS
    WHERE  ID= (SELECT GET_RESPUESTA_FROM_PREGUNTA ("DÓNDE ESTÁ VIGO?"));